error_reading_dataframe = ArgumentError("\"/home/users/nticea/code/QuasiperiodicSuperconductivity/data_collection/phase_diagram/data/17L_ΦQ_LGE_2023-07-11_22:28:20.csv\" is not a valid file or doesn't exist")
Finding Tc using LGE
s-wave configuration
λ = 0.38914131709593686
I've returned
s-wave configuration
λ = 0.4821148943623995
error_reading_dataframe = ArgumentError("\"/home/users/nticea/code/QuasiperiodicSuperconductivity/data_collection/phase_diagram/data/17L_ΦQ_LGE_2023-07-16_17:30:21.csv\" is not a valid file or doesn't exist")
